__author__ = 'marble_xu'

START_LEVEL_NUM = 1

ORIGINAL_CAPTION = 'GPT Powered: Security Defense'

# 逻辑基准尺寸（1x）
BASE_SCREEN_WIDTH = 800
BASE_SCREEN_HEIGHT = 600

# 渲染缩放因子（清晰度优先：1600x1200 = 2x）
RENDER_SCALE = 2

# 资源像素比例（1x 资源=1，2x 资源=2）
ASSET_PIXEL_RATIO = 1
# 资源缩放因子（渲染缩放 / 资源像素比例）
ASSET_SCALE = RENDER_SCALE / ASSET_PIXEL_RATIO

def scale(value):
    return int(round(value * RENDER_SCALE))

SCREEN_WIDTH = scale(BASE_SCREEN_WIDTH)
SCREEN_HEIGHT = scale(BASE_SCREEN_HEIGHT)
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

GRID_X_LEN = 9
GRID_Y_LEN = 5
BASE_GRID_X_SIZE = 80
BASE_GRID_Y_SIZE = 100
GRID_X_SIZE = scale(BASE_GRID_X_SIZE)
GRID_Y_SIZE = scale(BASE_GRID_Y_SIZE)


WHITE        = (255, 255, 255)
NAVYBLUE     = ( 60,  60, 100)
SKY_BLUE     = ( 39, 145, 251)
BLACK        = (  0,   0,   0)
LIGHTYELLOW  = (234, 233, 171)
RED          = (255,   0,   0)
PURPLE       = (255,   0, 255)
GOLD         = (255, 215,   0)
GREEN        = (  0, 255,   0)
ORANGE       = (255, 165,   0)
TEAL         = ( 64, 224, 208)
LIGHT_BLUE   = (100, 149, 237)

SIZE_MULTIPLIER = 1.3

#GAME INFO DICTIONARY KEYS
CURRENT_TIME = 'current time'
LEVEL_NUM = 'level num'

#STATES FOR ENTIRE GAME
LOADING_SCREEN = 'loading screen'
LOGIN_SCREEN = 'login screen'
MAIN_MENU = 'main menu'
LOAD_SCREEN = 'load screen'
GAME_LOSE = 'game los'
GAME_VICTORY = 'game victory'
GAME_REPORT = 'game report'
LEVEL = 'level'

MAIN_MENU_IMAGE = 'MainMenu'
OPTION_ADVENTURE = 'Adventure'
GAME_LOOSE_IMAGE = 'GameLoose'
GAME_VICTORY_IMAGE = 'GameVictory'

#MAP COMPONENTS
BACKGROUND_NAME = 'Background'
BACKGROUND_TYPE = 'background_type'
INIT_SUN_NAME = 'init_sun_value'
ZOMBIE_LIST = 'zombie_list'

MAP_EMPTY = 0
MAP_EXIST = 1

BASE_BACKGROUND_OFFSET_X = 220
BASE_MAP_OFFSET_X = 35
BASE_MAP_OFFSET_Y = 100
BACKGROUND_OFFSET_X = scale(BASE_BACKGROUND_OFFSET_X)
MAP_OFFSET_X = scale(BASE_MAP_OFFSET_X)
MAP_OFFSET_Y = scale(BASE_MAP_OFFSET_Y)

#MENUBAR
CHOOSEBAR_TYPE = 'choosebar_type'
CHOOSEBAR_STATIC = 0
CHOOSEBAR_MOVE = 1
CHOSSEBAR_BOWLING = 2
MENUBAR_BACKGROUND = 'ChooserBackground'
MOVEBAR_BACKGROUND = 'MoveBackground'
PANEL_BACKGROUND = 'PanelBackground'
START_BUTTON = 'StartButton'
CARD_POOL = 'card_pool'

MOVEBAR_CARD_FRESH_TIME = 6000
CARD_MOVE_TIME = 60

# 标准卡片参考尺寸（用于计算 HD 图片的缩放目标）
BASE_CARD_REF_WIDTH = 64
BASE_CARD_REF_HEIGHT = 90
CARD_REF_WIDTH = scale(BASE_CARD_REF_WIDTH)
CARD_REF_HEIGHT = scale(BASE_CARD_REF_HEIGHT)

# 高清图片判断阈值（超过此尺寸认为是高清）
HD_CARD_WIDTH_THRESHOLD = BASE_CARD_REF_WIDTH * 2
HD_CARD_HEIGHT_THRESHOLD = BASE_CARD_REF_HEIGHT * 2

#PLANT INFO
PLANT_IMAGE_RECT = 'plant_image_rect'
CAR = 'car'
SUN = 'Sun'
SUNFLOWER = 'SunFlower'
PEASHOOTER = 'Peashooter'
SNOWPEASHOOTER = 'SnowPea'
WALLNUT = 'WallNut'
CHERRYBOMB = 'CherryBomb'
THREEPEASHOOTER = 'Threepeater'
REPEATERPEA = 'RepeaterPea'
CHOMPER = 'Chomper'
CHERRY_BOOM_IMAGE = 'Boom'
PUFFSHROOM = 'PuffShroom'
POTATOMINE = 'PotatoMine'
SQUASH = 'Squash'
SPIKEWEED = 'Spikeweed'
JALAPENO = 'Jalapeno'
SCAREDYSHROOM = 'ScaredyShroom'
SUNSHROOM = 'SunShroom'
ICESHROOM = 'IceShroom'
HYPNOSHROOM = 'HypnoShroom'
WALLNUTBOWLING = 'WallNutBowling'
REDWALLNUTBOWLING = 'RedWallNutBowling'

PLANT_HEALTH = 5
WALLNUT_HEALTH = 30
WALLNUT_CRACKED1_HEALTH = 20
WALLNUT_CRACKED2_HEALTH = 10
WALLNUT_BOWLING_DAMAGE = 10

PRODUCE_SUN_INTERVAL = 5000
FLOWER_SUN_INTERVAL = 15000
SUN_LIVE_TIME = 7000
SUN_VALUE = 25

ICE_SLOW_TIME = 2000

FREEZE_TIME = 7500
ICETRAP = 'IceTrap'

#PLANT CARD INFO
CARD_SUNFLOWER = 'card_sunflower'
CARD_PEASHOOTER = 'card_peashooter'
CARD_SNOWPEASHOOTER = 'card_snowpea'
CARD_WALLNUT = 'card_wallnut'
CARD_CHERRYBOMB = 'card_cherrybomb'
CARD_THREEPEASHOOTER = 'card_threepeashooter'
CARD_REPEATERPEA = 'card_repeaterpea'
CARD_CHOMPER = 'card_chomper'
CARD_PUFFSHROOM = 'card_puffshroom'
CARD_POTATOMINE = 'card_potatomine'
CARD_SQUASH = 'card_squash'
CARD_SPIKEWEED = 'card_spikeweed'
CARD_JALAPENO = 'card_jalapeno'
CARD_SCAREDYSHROOM = 'card_scaredyshroom'
CARD_SUNSHROOM = 'card_sunshroom'
CARD_ICESHROOM = 'card_iceshroom'
CARD_HYPNOSHROOM = 'card_hypnoshroom'
CARD_REDWALLNUT = 'card_redwallnut'

#BULLET INFO
BULLET_PEA = 'PeaNormal'
BULLET_PEA_ICE = 'PeaIce'
BULLET_MUSHROOM = 'BulletMushRoom'
BULLET_DAMAGE_NORMAL = 1

#ZOMBIE INFO
ZOMBIE_IMAGE_RECT = 'zombie_image_rect'
ZOMBIE_HEAD = 'ZombieHead'
NORMAL_ZOMBIE = 'Zombie'
CONEHEAD_ZOMBIE = 'ConeheadZombie'
BUCKETHEAD_ZOMBIE = 'BucketheadZombie'
FLAG_ZOMBIE = 'FlagZombie'
NEWSPAPER_ZOMBIE = 'NewspaperZombie'
BOOMDIE = 'BoomDie'

LOSTHEAD_HEALTH = 5
NORMAL_HEALTH = 10
FLAG_HEALTH = 15
CONEHEAD_HEALTH = 20
BUCKETHEAD_HEALTH = 30
NEWSPAPER_HEALTH = 15

ATTACK_INTERVAL = 1000
ZOMBIE_WALK_INTERVAL = 70

ZOMBIE_START_X = SCREEN_WIDTH + scale(50)

#STATE
IDLE = 'idle'
FLY = 'fly'
EXPLODE = 'explode'
ATTACK = 'attack'
ATTACKED = 'attacked'
DIGEST = 'digest'
WALK = 'walk'
DIE = 'die'
CRY = 'cry'
FREEZE = 'freeze'
SLEEP = 'sleep'

#LEVEL STATE
CHOOSE = 'choose'
PLAY = 'play'

#BACKGROUND
BACKGROUND_DAY = 0
BACKGROUND_NIGHT = 1

#LANGUAGE
LANGUAGE_ZH_CN = 'zh_CN'
LANGUAGE_EN_US = 'en_US'

#ZOMBIE SCORES
ZOMBIE_SCORES = {
    NORMAL_ZOMBIE: 10,
    FLAG_ZOMBIE: 15,
    NEWSPAPER_ZOMBIE: 20,
    CONEHEAD_ZOMBIE: 25,
    BUCKETHEAD_ZOMBIE: 50
}

#GAME MODE
GAME_MODE_NORMAL = 'normal'
GAME_MODE_CRAZY = 'crazy'
CRAZY_MODE_DURATION = 120000  # 120 seconds in milliseconds
